repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3  # Use the latest version
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
